apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-postgres
  labels:
    db: cns-postgres
spec:
  selector:
    matchLabels:
      db: cns-postgres
  template:
    metadata:
      labels:
        db: cns-postgres
    spec:
      containers:
        - name: cns-postgres
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: 123456 
            - name: POSTGRES_DB
              value: cns-catalog
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: cns-postgres
  labels:
    db: cns-postgres
spec:
  type: ClusterIP
  selector:
    db: cns-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432