version: '3'
services:
  cns-catalog-service:
    depends_on:
      - cns-postgres
    image: cns-catalog-service
    container_name: cns-catalog-service
    environment:
      BPL_JVM_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://cns-postgres:5432/cns-catalog
      SPRING_CLOUD_CONFIG_URI: http://cns-config-service:8888
    ports:
      - "9001:9001"
      - "8001:8001"
    networks:
      - catalog-network
  cns-order-service:
    depends_on:
      - cns-postgres
    image: cns-order-service
    container_name: cns-order-service
    environment:
      BPL_JVM_THREAD_COUNT: 50
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 8001
      API_CATALOG_SERVICE_URI: http://cns-catalog-service:9001
      SPRING_CLOUD_CONFIG_URI: http://cns-config-service:8888
      SPRING_R2DBC_URL: r2dbc:postgresql://cns-postgres:5432/cns-order
      SPRING_FLYWAY_URL: jdbc:postgresql://cns-postgres:5432/cns-order
    ports:
      - "9002:9002"
      - "8002:8002"
    networks:
      - catalog-network
  cns-config-service:
    image: cns-config-service
    container_name: cns-config-service
    ports:
      - "8888:8888"
      - "9888:9888"
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      BPL_JVM_THREAD_COUNT: 50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      BPL_DEBUG_ENABLED: true
      BPL_DEBUG_PORT: 9888
  cns-postgres:
    image: postgres:13.3
    container_name: cns-postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - catalog-network
  cns-redis:
    image: "redis:latest"
    container_name: "cns-redis"
    ports:
      - "6379:6379"

networks:
  catalog-network:
    driver: bridge
